# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 951005242b2bc02b7944015c4c529b442f3ce0efab083812998815cab1a7f0ad44eb96140cd790396266db8d70c7664d688899469da56ba9860852284bf4b081

test:
  secret_key_base: 67eec93f81c72e038b50ffcc6581add920605b7e4b42b327c414c029355c444b7b3c6731ca2e6b67a978b0e1a8a6355d2e201d84466b32f27a6b85394e8e875d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
